### ISSUE TITLE
Design:  Track and Log Results for Continuous Improvement

### ISSUE THREAD

**Issue by csmangum** [csmangum/AgenticPoker#1]
## Problem Statement
While the current system has basic logging, we need more structured data collection and analysis capabilities to:
1. Evaluate agent performance across games
2. Analyze decision-making patterns
3. Identify areas for improvement in agent strategies
4. Compare different agent configurations
5. Track the effectiveness of LLM prompts

## Current Implementation
We have basic logging in:
- Game actions and outcomes
```python:game/game.py
startLine: 259
endLine: 304
```
- Agent decisions and LLM interactions
```python:agents/llm_agent.py
startLine: 253
endLine: 297
```

#### Game-Level Metrics
- Win/loss records
- Final chip counts
- Number of hands played
- Blind levels reached
- Duration of game
- Player elimination order

#### Player-Level Metrics
- Action frequencies (fold/call/raise percentages)
- Bluff attempts and success rates
- Average bet sizing
- Position-based statistics
- Showdown win rate
- All-in success rate

#### Decision-Level Metrics
- LLM prompts and responses
- Decision confidence scores
- Processing time per decision
- Memory retrievals and their relevance
- Strategy adjustments and their outcomes

### 2. Data Storage Structure

Create new database models for:
```python
class GameSession(Base):
    """Tracks overall game session statistics"""
    id = Column(Integer, primary_key=True)
    session_id = Column(String, unique=True)
    start_time = Column(DateTime)
    end_time = Column(DateTime)
    total_hands = Column(Integer)
    winner = Column(String)
    config = Column(JSON)  # Store game configuration

class PlayerPerformance(Base):
    """Tracks individual player performance"""
    id = Column(Integer, primary_key=True)
    session_id = Column(String, ForeignKey('game_session.session_id'))
    player_name = Column(String)
    starting_chips = Column(Integer)
    final_chips = Column(Integer)
    hands_played = Column(Integer)
    hands_won = Column(Integer)
    total_bets = Column(Integer)
    total_winnings = Column(Integer)
    strategy_style = Column(String)
    cognitive_config = Column(JSON)

class DecisionLog(Base):
    """Tracks individual AI decisions and outcomes"""
    id = Column(Integer, primary_key=True)
    session_id = Column(String)
    hand_id = Column(Integer)
    player_name = Column(String)
    prompt = Column(Text)
    response = Column(Text)
    decision = Column(String)
    confidence = Column(Float)
    processing_time = Column(Float)
    context = Column(JSON)  # Game state when decision was made
    outcome = Column(JSON)  # Result of the decision
```

### 3. Analysis Tools

Create utilities for:
1. Performance trend analysis
2. Strategy effectiveness evaluation
3. Decision quality assessment
4. Prompt effectiveness analysis
5. Memory usage optimization

### 4. Visualization Dashboard

Build a simple web interface to:
- View game session results
- Compare agent performances
- Analyze decision patterns
- Track learning progress
- Identify areas for improvement

## Implementation Steps

1. Create new database models and migrations
2. Enhance existing logging in game engine
3. Add metrics collection to LLMAgent class
4. Build analysis utilities
5. Create visualization dashboard
6. Add configuration for logging levels

## Acceptance Criteria

- [ ] All game sessions are logged with complete metrics
- [ ] Each AI decision is recorded with context and outcome
- [ ] Analysis tools can generate meaningful insights
- [ ] Dashboard shows key performance indicators
- [ ] Data collection has minimal impact on game performance
- [ ] Export functionality for offline analysis

## Technical Considerations

1. Database performance with large datasets
2. Storage requirements for LLM prompts/responses
3. Query optimization for analysis
4. Data retention policies
5. Privacy considerations for stored data

## Related Files
```python:main.py
startLine: 13
endLine: 24
```
```python:data/model.py
startLine: 190
endLine: 217
```

## Questions to Consider

1. How long should we retain detailed decision logs?
2. What metrics are most important for improving agent performance?
3. How can we efficiently store and query large amounts of game data?
4. What visualization tools would be most helpful for analysis?
